# Generated by Django 4.0.2 on 2022-02-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='skills',
            field=models.ManyToManyField(to='persona.Skills'),
        ),
    ]
