# Generated by Django 4.0.2 on 2022-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_skills_empleado_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
