# Generated by Django 4.0.2 on 2022-02-10 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cv',
            field=ckeditor.fields.RichTextField(default='Text'),
            preserve_default=False,
        ),
    ]
